/:
      dispatch:
                controller: "Index"
                action: "index"
      callback: "dispatch"

/index:
      dispatch:
                controller: "Index"
                action: "index"
       
/index/id:
      dispatch:
            controller: 'Index'
            action: 'id'
        
# заглушка
/favicon.ico:
      dispatch:
            controller: 'Index'
            action: 'index'
        
/about:
      dispatch:
            controller: 'About'
            action: 'about'
        
/portfolio:
      dispatch:
            controller: 'Portfolio'
            action: 'portfolio'

/news:
      dispatch:
            controller: 'News'
            action: 'news'

/services:
      dispatch:
            controller: 'Services'
            action: 'services'

/comments:
      dispatch:
            controller: 'Comments'
            action: 'comments'
        
/carousel/:action/:dir/:file:
            dispatch:
                  controller: 'Carousel'
            callback: "carousel"

        
/404:
      dispatch:
            controller: 'Location'
            action: 'error404'
        
/403:
      dispatch:
            controller: 'Location'
            action: 'error403'
        
/stop:
      dispatch:
            controller: 'Location'
            action: 'stopPage'
        
# ajax e-mail на странице блокировки
/subscription_lock_page:
      dispatch:
            controller: 'StubPage'
            action: 'toEmail'
        
/stubPage:
      dispatch:
            controller: 'StubPage'
            action: 'stubPage'
        
/login:
      dispatch:
            controller: 'Login'
            action: 'userLogin'
        
/exit:
      dispatch:
            controller: 'Login'
            action: 'userExit'
        
/admin:
      dispatch:
            controller: 'Admin'
            action: 'admin'
        
/redirect:
      dispatch:
            controller: 'Redirect'
            action: 'redirect'
        
/wm:
      dispatch:
            controller: 'Carousel'
            action: 'view'
        
/th:
      dispatch:
            controller: 'Carousel'
            action: 'thumb'
